title: This is a title for the site
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.863858022261411
  brandStrength: 0.5625
  lightness: 0.2931411473546177
  brandColors:
    - '#5D5242'
    - '#A38967'
    - '#CDAD7E'
    - '#171E21'
  rhythmicContrast: 0.9682656358927488
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: TDPersonalSite
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.91433
layout_spectrum: 0.2670251
